### ISSUE TITLE
There is no file "demo/REF_PROFILE_FILES/CMC.LOC643837.profile"

### ISSUE THREAD

**Issue by xiechengyong123** [opain/Predicting-TWAS-features#2]
Hello:
      I want to ask you a question. When I run the software, "awk: fatal: cannot open file `demo/REF_PROFILE_FILES/CMC.LOC643837.profile' for reading (No such file or directory)" appears. What's the matter?
     Thanks!

**Comment by opain** [comment]
Hi, this is probably because you are not specifying the --weights_dir parameter correctly. If you are not running the analysis in the repo folder, then you will need to specify the full path to the test_data/CMC.BRAIN.RNASEQ.
