### ISSUE TITLE
Error in { : task 1 failed - "cannot open the connection"

### ISSUE THREAD

**Issue by MIAO0916** [opain/Predicting-TWAS-features#4]
Calls: %dopar% -> <Anonymous>
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

Rscript FeaturePred.V2.0.R \
	--PLINK_prefix_chr	FeaturePred/PLINK_prefix_chr/1000G.EUR. \
	--weights FeaturePred/OA_synovium_v1.WH_fusion/OA_synovium_v1.WH_fusion.P01.pos \
	--weights_dir	FeaturePred/OA_synovium_v1.WH_fusion \
	--ref_ld_chr	FeaturePred/PLINK_prefix_chr/1000G.EUR. \
	--plink	plink \
	--ref_maf	FeaturePred/PLINK_prefix_chr/1000G.EUR. \
	--pigz pigz \
	--chr 1 \
	--output demo

Hi，could you plz tell me how can I solve this problem? where should I adjust?

BEST,
miaoz

**Comment by MIAO0916** [comment]
I have already solved this problem！
Now I want to share some tips：
First, make sure that the content of PANEL is consistent with  the path of WGT 
Then, if your pos file has some genes that don't work, be sure to remove it in the pos file and delete the corresponding rdat file
hope you all can apply this package successfully~

**Comment by opain** [comment]
Thanks for reporting your solution! I will try and improve the error reporting in the future.
